# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2,
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the
# same biological sample).If the column "strandedness" is present (which is optional),
# can be empty or has one of these values: none, yes or reverse. none is for unstranded
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse`
# which is referenced in STAR manual section 7, "Counting number of reads per gene".

units: units.tsv

trimming:
  # skip trimming: false or true
  skip: false
  # the sequencing adapter
  adapter: ACGGATCGATCGATCGATCGAT

ref:
  # the STAR index
  index: "data/ref/index"
  # gtf file with transcripts
  annotation: "data/ref/annotation.chr21.gtf"

pca:
  # activate pca: false or true
  activate: true
  # you can choose between a variance stabilizing transformation using either VST or rlog: VST or rlog
  # rlog tends to work better for smaller data sets whereas VST is usually better for medium-to-large data sets
  # default is rlog (VST needs at least 1000 genes)
  transformation: rlog
  labels:
    # columns of sample sheet to use for PCA
    - condition
    - time

meanSdPlot:
  # activate meanSdPlot: false or true
  activate: true
    # you can choose between a variance stabilizing transformation using either norm or VST or rlog: norm or VST or rlog
    # norm uses log2 with a pseudocount of 1 on normalized counts, rlog tends to work better for smaller data sets whereas VST is usually better for medium-to-large data sets
    # default is norm (VST needs at least 1000 genes)
  transformation: norm

heatmap:
  # heatmap of the count matrix
  # activate heatmap: false or true
  activate: true

dispersionPlot:
  # Plots the dispersion estimates
  # activate dispersionPlot: false or true
  activate: true

IndependentHypothesisWeighting:
  # Creates a pvalHistogram
  # This function creates a few diagonstic plots
  # activate IndependentHypothesisWeighting: false or true
  activate: true
  # nominal level for FDR control
  alpha: 0.05

diffexp:
  # The following will be mostly useful if you're unexperienced with designs
  standard:
    # creates useful contrasts for unexperienced users to work with
    # If you want to use advanced and don't want duplicates of contrasts I'd recommend setting it to false
    # createContrasts: false or true
    createContrasts: true
  # The following will be mostly useful if you already have some experience with designs (please keep it like this if you use standard)
  advanced:
    # log fold change shrinkage on results
    lfcShrink:
      # activate lfcShrink: false or true
      activate: false
      # possible types: normal, apeglm, ashr
      type: apeglm
    # alpha used for results, if not changed, it will always use 0.1
    alpha: 0.1
    # LRT with the ability to set a reduced model
    time:
      # are you testing for a Time Course Experiment: false or true
      activate: false
      # specify a reduced model for LRT, e.g. "design: ~ treatment + time + treatment:time" then you might want to use "reduced: ~ treatment + time"
      reduced: ~ 1
      # threshold for the color key range (has to be a numeric value)
      threshold: 5

    # formula design for the DESeqDataSet
    formula:
      design: ~ 1
      # enables group design by joining the factors: false or true
      # If you choose this option, you will have to change the contrasts, since you will only get to use grouped contrasts
      group: false

    # contrasts for the deseq2 results method
    contrasts:
      treated-vs-untreated:
        - treated
        - untreated
      4h-vs-8h:
        - 4h
        - 8h

# additional parameter arguments
params:
  star: ""
  cutadapt-se: ""
  cutadapt-pe: ""
